server:
  port: 9800
spring:
  redis:
    host: 192.168.9.205
    port: 6379
    password: admin
  datasource:
    druid:
      # 初始化大小、最小、最大连接数
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: admin
      stat:
        log-slow-sql: true
        slow-sql-millis: 2000
      wzq:
        url: jdbc:mysql://192.168.9.205/wzq
        username: sboxweb
        password: Sbox123456xZ
        driver-class-name: com.mysql.jdbc.Driver
        auto-reconnect: true
        max-active: 50
        test-on-borrow: true
      wzq1:
        url: jdbc:mysql://192.168.9.205/wzq1
        username: sboxweb
        password: Sbox123456xZ
        driver-class-name: com.mysql.jdbc.Driver
        auto-reconnect: true
        max-active: 50
        test-on-borrow: true
logging:
  level:
    org.springframework.web: ERROR
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: d:/logs/mySpring.log
com:
  zx:
    name: wzq
